### ISSUE TITLE
This looks interesting

### ISSUE THREAD

**Issue by andybak** [codewriter-packages/UniMob.UI#1]
Any code examples?

**Comment by vanifatovvlad** [comment]
Some code examples are located here https://github.com/vanifatovvlad/CodeWriter-Packages/tree/master/Assets/Samples/

**Comment by andybak** [comment]
Thanks. It might be useful to others to add that link the main README.

(Also - maybe add a repo description on https://github.com/vanifatovvlad/CodeWriter-Packages ? )
