### ISSUE TITLE
Using `AnimateTo` on TabController with Duration set to 0 never updates `Value`

### ISSUE THREAD

**Issue by Girildo** [codewriter-packages/UniMob.UI#16]
**Describe the bug**
A `TabController` a `Duration` of `0f` and will not update `TabController#Value` if `AnimateTo(int)` is used.

**Expected behavior**
Even if the transition is istantaneous, `Value`  kept in sync with `Index`

With `Duration` set to 0 the AnimationTicker is not added and therefore the assignment value is never reassigned.

**Desktop:** Windows 10
**Unity version:** 2021.
**UniMob version:** 2.3.0
**UniMob.UI version:** 0.5.2
**Other plugins installed:** UniTask, DoTween

**Comment by Girildo** [comment]
I find the API with Value/Index a bit confusing overall. Is there any reason to keep them both around?

**Comment by vanifatovvlad** [comment]
The `Value` changes smoothly and is primarily necessary for the animations which must be synchronized with the tab switching animation. 
The `Index` is needed when it is necessary to get the current state of the tabs without taking into account animation and dragging.
